### ISSUE TITLE
Event upload submit crash

### ISSUE THREAD

**Issue by kdhiman0309** [UCSD-CSE-210/UCSDEventHub#106]
This seems to be when logged in user is not organizer. Probably need to handle this.
[DoesNotExist at _submit_event_.pdf](https://github.com/UCSD-CSE-210/UCSDEventHub/files/1530957/DoesNotExist.at._submit_event_.pdf)

**Comment by nikhilym** [comment]
@kdhiman0309 this page will not even load when user is not organizer. I made the changes in page rendering so that a permission denied error is thrown. Can you check again if you are able to access the page (either through navbar or through url directly) and update the issue? I am assigning this issue to myself since I made couple of changes regarding this.

**Comment by nikhilym** [comment]
Tested to be working fine. Issue was with Django version. Closing it since @kdhiman0309 confirmed it to be working as expected.
