### ISSUE TITLE
Search API giving old results

### ISSUE THREAD

**Issue by kdhiman0309** [UCSD-CSE-210/UCSDEventHub#78]
Filter the results by current date.  Only show upcoming events (end date > current_time).

**Comment by nikhilym** [comment]
Added timezone supported filters for search events and upcoming events since current timezone is UTC in DB, but we will generally use PST. Currently this is hardcoded. Will create a different issue to handle TZ dynamically. The filters help in providing events that are from current day in PST rather than from current time
