### ISSUE TITLE
Refactoring Homepage page

### ISSUE THREAD

**Issue by kdhiman0309** [UCSD-CSE-210/UCSDEventHub#82]
Create a class similar to SearchListing for Homepage. Make changes to views.py and urls.py

**Comment by devykulk** [comment]
The homepage now calls the get rsvp api if the user is logged in instead of calling the upcoming events API. The UI changes for MyEvents tab will be handles in the base.html as they apply to all the pages and not just the homepage. Also, this task assumes that the get_rsvp API works correctly as expected.
