### ISSUE TITLE
Modify Search API 

### ISSUE THREAD

**Issue by devykulk** [UCSD-CSE-210/UCSDEventHub#85]
Modify the search API to allow search on hashtags, category, date/time, organization name and location

**Comment by nikhilym** [comment]
Need the specifics of how the search should behave, since we only have one input value but multiple attributes to apply filter on. What should happen for date/time search? should that be allowed? Also all other searches are case insensitive and not exact match, right?

@kdhiman0309 , @devykulk , @chandanatl , @kolasanichaitanya need your inputs.

**Comment by kolasanichaitanya** [comment]
I would say each attribute will be a part of get request and the final filter has tone AND of all. Better way is json but requires Javascript code to build such request from front end.

**Comment by nikhilym** [comment]
@kolasanichaitanya that means we have a separate attribute level search bar. As per @kdhiman0309 , we have only one search bar that can search for all attributes together.

**Comment by kolasanichaitanya** [comment]
Then it Just has to be a OR of every thing I guess

**Comment by nikhilym** [comment]
Date/Time is not considered for search. All other attributes will be searched with OR filter applied.

**Comment by nikhilym** [comment]
This commit fixes the following :
1. Search enhanced to filter by title, org name, location, hashtags. All
these are searched with an OR condtion.
2. The above mentioned filters are added with an AND condition to
current datetime object, so that only the upcoming events are shown
under Search
3. Duplicate events are removed and sorted with respect to start_date of
events.
